Fix QT GUI Inspector Sink center frequency & Arch Linux build issues
gnuradio/gr-inspector pull request #18
Opened 2018-03-01 09:00 UTC by karel-

I've combined two fixes into a single pull request here.

4456f15: forces the QT GUI Inspector Sink to rebuild its frequency vector when center frequency has been changed.

8fa4b5a: reorders the qwt names in FindQwt.cmake to prevent linking with the wrong libraries. I had problems in Arch Linux because gr-inspector found the [qwt](https://www.archlinux.org/packages/extra/x86_64/qwt/) package while it should be finding the [qwt-qt4](https://aur.archlinux.org/packages/qwt-qt4/) from AUR. This didn't prevent gr-inspector from building but gave confusing warnings and crashed gnuradio-companion.

```sh
Warning: restarting the docstring loader (crashed while loading 'inspector_ofdm_synchronizer_cc')
Warning: restarting the docstring loader (crashed while loading 'inspector_ofdm_zkf_c')
Warning: restarting the docstring loader (crashed while loading 'inspector_qtgui_sink_vf')
Warning: restarting the docstring loader (crashed while loading 'inspector_signal_detector_cvf')
Warning: restarting the docstring loader (crashed while loading 'inspector_signal_extractor_c')
Warning: docstring loader crashed too often
[1]    4880 segmentation fault (core dumped)  gnuradio-companion
```

2018-03-03 12:48 UTC, sbmueller commented
@karel- Thank you for the PR! I will investigate the changes and come back with any questions.

2018-03-15 18:27 UTC, sbmueller requested changes
@karel- could you alter the PR according to my comments?

2018-03-15 18:27 UTC, sbmueller commented on lib/qtgui_inspector_sink_vf_impl.h
> +        d_main_gui->set_axis_x(-d_samp_rate/2, d_samp_rate/2-1);
You're right, the vector won't get recalculated just by `set_cfreq()`. Since the vector should be recalculated *every time* when `cfreq` is set again, I would propose `set_axis_x()` is called within `inspector_form::set_cfreq()` instead of having to call both methods every time. This also makes the call redundant occurring in `qtgui_inspector_sink_vf_impl.cc` l. 135.

2018-03-19 09:30 UTC, karel- commented
@sbmueller sure, there you go.

2018-04-14 16:30 UTC, sbmueller commented
Sorry @karel- for the delay.
I have not put enough thought in this last time. `set_cfreq()` should only have the new center frequency as argument, not the sampling rate as well. Could you revert the latest commit? It seems you already where ahead of my thinking there :)

2018-04-18 06:13 UTC, karel- commented
@sbmueller no problem. Reverted the last commit.

2018-04-30 08:15 UTC, karel- commented
Hey @sbmueller! In case you don't care too much about the order in which headers are included, I propose to include Python header first to prevent the annoying warnings.

https://bugs.python.org/issue1045893

2018-04-30 14:06 UTC, sbmueller approved these changes

2018-04-30 14:07 UTC, sbmueller commented
Hi @karel- sorry for letting you wait that long. Looks fine, I will merge now.

2018-04-30 14:07 UTC, merged