Dev 3.8
gnuradio/gr-inspector pull request #34
Opened 2019-11-23 10:45 UTC by primercuervo

Further efforts in direction 3.8 support.

2019-11-23 17:01 UTC, sbmueller requested changes
Thank you for the effort to accelerate gr-inspector's porting to 3.8 :)
Can you address some remarks I have added to the code? I'm trying to wrap my head around CMake and Qt again.

2019-11-23 17:01 UTC, sbmueller commented on CMakeLists.txt
> +find_package(Qt5Widgets REQUIRED )
I think a space slipped in here

2019-11-23 17:01 UTC, sbmueller commented on lib/CMakeLists.txt
> +                      Qt5::Widgets
Question: do you know why we don't have to link against Qt5::Core? E.g. `QTimer` is used from there.

2019-11-23 17:01 UTC, sbmueller commented on CMakeLists.txt
> -find_package(Qt5 COMPONENTS Core Widgets REQUIRED)
From this resource (https://blog.kitware.com/cmake-finding-qt5-the-right-way/) this would be a good way to do this. Why did you change it?

2019-11-23 17:01 UTC, sbmueller commented on CMakeLists.txt
> +find_package(PythonLibs 3)
Is this needed? I manage to `cmake ..`, `make` and `make test` successfully without this.

2019-11-23 17:01 UTC, sbmueller commented on CMakeLists.txt
> +set(QT_INCLUDE_DIRS ${Qt5Widgets_INCLUDE_DIRS})
Same here, I'm wondering why these variables are set. They don't seem to get used anywhere and `make test` works fine without them.

2019-11-23 17:01 UTC, sbmueller commented on lib/CMakeLists.txt
> +                      gnuradio::gnuradio-runtime qwt::qwt Qt5::Widgets Python::Python)
I like the one-entry-per-line statement of 7562b2c :)

2019-11-23 17:01 UTC, sbmueller commented on lib/inspector_form.h
>  #include <QtGui/QtGui>
```
#include <QtWidgets>
#include <QtGui>
```
should be the correct directive here (https://doc.qt.io/qt-5/qtwidgets-index.html)

2019-11-23 17:01 UTC, sbmueller commented on lib/ofdm_bouzegzi_c_impl.h
> +                            const std::vector<int> &beta);
Flake8 would say "Continuation line over-indented for visual indent" :stuck_out_tongue: Can you remove one space to have identical indents?

2019-11-23 17:01 UTC, sbmueller commented on lib/ofdm_bouzegzi_c_impl.h
> +         gr_vector_void_star &output_items);
Can you adjust to visual indent?

2019-11-23 21:19 UTC, primercuervo commented
Hey @sbmueller,

thanks for the comments. The CMake stuff that was leftover was my bad: I was just testing things out to get the hang of the component. I took the superfluous vars out and added the QT5 components as suggested.

All other comments are as well addressed. Let me know if there's something I missed.

For formatting shennanigans: I have my vim to autoformat on save, but this OOT has different indentation rules, so I turned it of and didn't re-check. I'd suggest to jump on the .clang-format train and apply the [GNU Radio format file ](https://github.com/gnuradio/gnuradio/blob/master/.clang-format). I can help with that as well if you see it fit

2019-11-24 10:05 UTC, sbmueller commented
Hello @primercuervo , thanks so much for updating! All looks pretty good now.
In terms of formatting, I'm happy do adopt the new format file of GR. Since this branch will generate a big diff to master anyway, I'd suggest to to one formatting commit after all functional issues are resolved. I guess you can go ahead and already amend the formatting to the files you touched, or wait until that formatting commit. What do you reckon @primercuervo ?

2019-11-24 10:25 UTC, primercuervo commented
@sbmueller I'd make the formatting the last thing, after functional testing is done. That would make melding easier for random cherry-picks in the process. That includes my current changes as well (i.e. I'd keep them as they are now until the whole formatting takes place).

2019-11-24 11:03 UTC, sbmueller approved these changes

2019-11-24 11:16 UTC, sbmueller commented
Merged manually

2019-11-24 11:16 UTC, closed without merging